DROP TABLE IF EXISTS WROX_MAILLIST_USER;

CREATE TABLE WROX_MAILLIST_USER (
    EMAIL_ADDR  VARCHAR(100)      NOT NULL,
    IS_DIGEST   TINYINT(1)        NOT NULL  DEFAULT 0,

    PRIMARY KEY (EMAIL_ADDR)
)
ENGINE=MyISAM DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs;
